version: "3.7"

services:
    app:
        build:
            args:
                user: ecjasso
                uid: 1000
            context: .
            dockerfile: dockerfile
        image: laravel-app
        container_name: backend        
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - laravel
    db:
        image: mysql:5.7
        container_name: db        
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - ./docker-compose/mysql:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
